### ISSUE TITLE
Match two fingerprints

### ISSUE THREAD

**Issue by dan-developer** [usnistgov/biomdi#1]
I'm looking for a piece of code that can read an image, create an iso template and that can then compare two readings and say whether it is the same finger or not. I ended up falling here, but there is no documentation on.

**Comment by gfiumara** [comment]
You need to extract features from the image before you can encode the features into an ISO template. `mkfmr` in this repo can encode the features. There are several feature extractors, but not many open source ([`mindtct`](https://www.nist.gov/services-resources/software/nist-biometric-image-software-nbis) and [FingetJet](https://github.com/FingerJetFXOSE/FingerJetFXOSE)). Then you need a matcher that can parse the templates and output a similarity score. Again, [many matching algorithms](https://pages.nist.gov/minex/results/tables/), but not many open source ([`bozorth3`](https://www.nist.gov/services-resources/software/nist-biometric-image-software-nbis) is, although uses it's own template that can be derived from the ISO template).

**Comment by dan-developer** [comment]
Where can I get the bozorth3 and mindtct executable or shared librarie (.so or .dll)?
